version: "3.7"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - /mnt/disco1/media:/media/disco1
      - /mnt/disco2/media:/media/disco2
      - ./config/jellyfin:/config
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    ports:
      - "8180:8180"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Cordoba
      - WEBUI_PORT=8180
    volumes:
      - ./config/qbittorrent:/config
      - /mnt/disco2/descargas:/downloads
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Cordoba
    volumes:
      - ./config/jackett:/config
      - /mnt/disco2/descargas:/downloads
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Cordoba
    volumes:
      - ./config/sonarr:/config
      - /mnt/disco1/media/series:/tv1
      - /mnt/disco2/media/series:/tv2
      - /mnt/disco2/descargas:/downloads
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Cordoba
    volumes:
      - ./config/radarr:/config
      - /mnt/disco1/media/peliculas:/movies1
      - /mnt/disco2/media/peliculas:/movies2
      - /mnt/disco2/descargas:/downloads
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Cordoba
    volumes:
      - ./config/bazarr:/config
      - /mnt/disco1/media:/media1
      - /mnt/disco2/media:/media2
      - /mnt/disco1/media/series:/tv1        # para Sonarr
      - /mnt/disco2/media/series:/tv2        # para Sonarr
      - /mnt/disco1/media/peliculas:/movies1 # para Radarr
      - /mnt/disco2/media/peliculas:/movies2 # para Radarr
      - /mnt/disco2/descargas:/downloads
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup

  telegram-bot:
    image: ghcr.io/autobrr/autobrr:latest
    container_name: autobrr
    depends_on:
      - qbittorrent
    ports:
      - "7474:7474"
    volumes:
      - ./config/autobrr:/config
    restart: unless-stopped
    # A integrar con tu bot de Telegram (configuración desde el panel de autobrr)

  discord-webhook:
    image: curlimages/curl
    container_name: discord_notify
    entrypoint: ""
    command: >
      sh -c "while true; do sleep 3600; done"
    # Placeholder para integrar con Webhook de Discord usando curl desde Sonarr/Radarr/Bazarr

# Red: bridge por defecto
